camel:
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

zeebe:
  client:
    max-execution-threads: 100
    number-of-workers: 5
    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
  broker:
    contactpoint: "localhost:26500"

ams:
  local:
    enabled: true
  timeout: 60000

pesacore:
  base-url: https://opswebsitetest.oaftemp.org
  auth-header: 51f56774-8ef6-11ec-b909-0242ac120002
  endpoint:
    verification: /api/paymentHub/Verification
    confirmation: /api/paymentHub/Confirmation
    client-details: /Api/globalMM/Client
  countries:
    - country-id: ${PESACORE_COUNTRY_0_ID:1}
      currency: ${PESACORE_COUNTRY_0_CURRENCY:RWF}
    - country-id: 454
      currency: MWK

management:
  endpoint:
    health:
      probes:
        enabled: true
      liveness:
        enabled: true
      readiness:
        enabled: true
logging:
  level:
    ROOT: INFO
